name: "Issue Classifier"
description: "Classify issues by label with Hugging Face Inference Endpoint"
author: "August-murr"

inputs:
  token:
    description: "The GITHUB_TOKEN secret"
    required: false
    default: ${{ github.token }}
  hf-api-key:
    description: "The HF API key secret"
    required: true
  model-name:
    description: "The model name to use, eg meta-llama/Llama-3.3-70B-Instruct"
    required: false
    default: "meta-llama/Llama-3.3-70B-Instruct"

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-python@v4
    with:
      python-version: '3.11'
  - name: Install dependencies
    shell: "bash"
    run: pip install huggingface_hub PyGithub
  - name: Create calendar event
    shell: "bash"
    env:
      GITHUB_TOKEN: ${{ inputs.token }}
      HF_API_KEY: ${{ inputs.hf-api-key }}
      MODEL_NAME: ${{ inputs.model-name }}
    run: python "$GITHUB_ACTION_PATH/label.py"
